name: Scrape IVU and Publish ICS

on:
  schedule:
    - cron: '0 5 * * *'   # diario 05:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 icalendar pytz

      - name: Install Playwright browsers & OS deps
        run: |
          python -m playwright install chromium
          python -m playwright install-deps

      - name: Run scraper
        env:
          IVU_USER: ${{ secrets.IVU_USER }}
          IVU_PASS: ${{ secrets.IVU_PASS }}
        run: |
          mkdir -p debug
          set -e
          python scrape_and_publish.py > output.txt || (echo "SCRAPER FAILED"; set +e; cat output.txt; exit 1)
          cat output.txt || true
          mkdir -p calendars
          mv -f turnos_*.ics calendars/ || true

      - name: Upload debug artifacts (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            debug/**
            output.txt
          if-no-files-found: ignore

      - name: Publish to gh-pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./calendars
