name: Scrape IVU and Publish ICS

on:
  schedule:
    - cron: '0 5 * * *'   # ejecución diaria 05:00 UTC (ajusta)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 icalendar pytz
          playwright install chromium

      - name: Run scraper
        env:
          IVU_USER: ${{ secrets.IVU_USER }}
          IVU_PASS: ${{ secrets.IVU_PASS }}
        run: |
          python scrape_and_publish.py > output.txt || (cat output.txt && exit 1)
          cat output.txt
          FILES=$(grep -oP '(?<=GENERATED_FILES=).+' output.txt || echo "")
          echo "found=$FILES" >> $GITHUB_OUTPUT

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./calendars
